/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormAddFunctionary: typeof import('./src/components/forms/Create/formAddFunctionary.vue')['default']
    FormAddSeedbed: typeof import('./src/components/forms/Create/formAddSeedbed.vue')['default']
    FormAddStudent: typeof import('./src/components/forms/Create/formAddStudent.vue')['default']
    FormAddUser: typeof import('./src/components/forms/Create/formAddUser.vue')['default']
    FormCreateGeneral: typeof import('./src/components/forms/Create/formCreateGeneral.vue')['default']
    FormCreateGroupProfile: typeof import('./src/components/forms/Create/Groups/formCreateGroupProfile.vue')['default']
    FormCreateGroups: typeof import('./src/components/forms/Create/Groups/formCreateGroups.vue')['default']
    FormCreatePeriod: typeof import('./src/components/forms/Create/Periods/formCreatePeriod.vue')['default']
    FormCreatePeriods: typeof import('./src/components/forms/Create/Periods/formCreatePeriods.vue')['default']
    FormCreateRole: typeof import('./src/components/forms/Create/Roles/formCreateRole.vue')['default']
    FormCreateRoles: typeof import('./src/components/forms/Create/Roles/formCreateRoles.vue')['default']
    FormCreateUser: typeof import('./src/components/forms/Create/Users/formCreateUser.vue')['default']
    FormCreateUsers: typeof import('./src/components/forms/Create/Users/formCreateUsers.vue')['default']
    FormDeleteGeneral: typeof import('./src/components/forms/Delete/formDeleteGeneral.vue')['default']
    FormLogin: typeof import('./src/components/forms/formLogin.vue')['default']
    FormUpdateFunctionary: typeof import('./src/components/forms/Patch/formUpdateFunctionary.vue')['default']
    FormUpdateGeneral: typeof import('./src/components/forms/Update/formUpdateGeneral.vue')['default']
    FormUpdateGroup: typeof import('./src/components/forms/Patch/formUpdateGroup.vue')['default']
    FormUpdateGroups: typeof import('./src/components/forms/Update/Groups/formUpdateGroups.vue')['default']
    FormUpdatePeriod: typeof import('./src/components/forms/Patch/formUpdatePeriod.vue')['default']
    FormUpdateSeedbed: typeof import('./src/components/forms/Patch/formUpdateSeedbed.vue')['default']
    FormUploadStudent: typeof import('./src/components/forms/Patch/formUploadStudent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingBtn: typeof import('./src/components/loadingBtn.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    QuickActions: typeof import('./src/components/quickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAcademicPeriods: typeof import('./src/components/tables/general/tableAcademicPeriods.vue')['default']
    TableCoordinator: typeof import('./src/components/tables/lounge/tableCoordinator.vue')['default']
    TableEmployees: typeof import('./src/components/tables/general/tableEmployees.vue')['default']
    TableExternal: typeof import('./src/components/tables/lounge/tableExternal.vue')['default']
    TableFunctionaries: typeof import('./src/components/tables/general/tableFunctionaries.vue')['default']
    TableGroups: typeof import('./src/components/tables/general/tableGroups.vue')['default']
    TableGroupsByPeriod: typeof import('./src/components/tables/dynamic/tableGroupsByPeriod.vue')['default']
    TableMembers: typeof import('./src/components/tables/lounge/tableMembers.vue')['default']
    TableRole: typeof import('./src/components/tables/roles/tableRole.vue')['default']
    TableRoles: typeof import('./src/components/tables/roles/tableRoles.vue')['default']
    TableSeedbeds: typeof import('./src/components/tables/general/tableSeedbeds.vue')['default']
    TableSeedbedsByGroup: typeof import('./src/components/tables/dynamic/tableSeedbedsByGroup.vue')['default']
    TableStudents: typeof import('./src/components/tables/general/tableStudents.vue')['default']
    TableStudentsSeedbeds: typeof import('./src/components/tables/dynamic/tableStudentsSeedbeds.vue')['default']
    TableTeachers: typeof import('./src/components/tables/lounge/tableTeachers.vue')['default']
    TableUsers: typeof import('./src/components/tables/users/tableUsers.vue')['default']
  }
}
