/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormAddFunctionary: typeof import('./src/components/forms/Post/formAddFunctionary.vue')['default']
    FormAddGroup: typeof import('./src/components/forms/Post/formAddGroup.vue')['default']
    FormAddPeriod: typeof import('./src/components/forms/Post/formAddPeriod.vue')['default']
    FormAddSeedbed: typeof import('./src/components/forms/Post/formAddSeedbed.vue')['default']
    FormAddStudent: typeof import('./src/components/forms/Post/formAddStudent.vue')['default']
    FormAddUser: typeof import('./src/components/forms/Post/formAddUser.vue')['default']
    FormCreateGeneral: typeof import('./src/components/forms/Post/formCreateGeneral.vue')['default']
    FormDeleteGeneral: typeof import('./src/components/forms/Delete/formDeleteGeneral.vue')['default']
    FormLogin: typeof import('./src/components/forms/formLogin.vue')['default']
    FormUpdateFunctionary: typeof import('./src/components/forms/Patch/formUpdateFunctionary.vue')['default']
    FormUpdateGeneral: typeof import('./src/components/forms/Put/formUpdateGeneral.vue')['default']
    FormUpdateGlobalGroup: typeof import('./src/components/forms/Put/Groups/formUpdateGlobalGroup.vue')['default']
    FormUpdateGroup: typeof import('./src/components/forms/Patch/formUpdateGroup.vue')['default']
    FormUpdatePeriod: typeof import('./src/components/forms/Patch/formUpdatePeriod.vue')['default']
    FormUpdateSeedbed: typeof import('./src/components/forms/Patch/formUpdateSeedbed.vue')['default']
    FormUploadStudent: typeof import('./src/components/forms/Patch/formUploadStudent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoadingBtn: typeof import('./src/components/loadingBtn.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    QuickActions: typeof import('./src/components/quickActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableAssestmentPeriods: typeof import('./src/components/tables/general/tableAssestmentPeriods.vue')['default']
    TableCoordinator: typeof import('./src/components/tables/lounge/tableCoordinator.vue')['default']
    TableEmployees: typeof import('./src/components/tables/general/tableEmployees.vue')['default']
    TableExternal: typeof import('./src/components/tables/lounge/tableExternal.vue')['default']
    TableFunctionaries: typeof import('./src/components/tables/general/tableFunctionaries.vue')['default']
    TableGroups: typeof import('./src/components/tables/general/tableGroups.vue')['default']
    TableGroupsByPeriod: typeof import('./src/components/tables/dynamic/tableGroupsByPeriod.vue')['default']
    TableMembers: typeof import('./src/components/tables/lounge/tableMembers.vue')['default']
    TableSeedbeds: typeof import('./src/components/tables/general/tableSeedbeds.vue')['default']
    TableSeedbedsByGroup: typeof import('./src/components/tables/dynamic/tableSeedbedsByGroup.vue')['default']
    TableStudents: typeof import('./src/components/tables/general/tableStudents.vue')['default']
    TableStudentsSeedbeds: typeof import('./src/components/tables/dynamic/tableStudentsSeedbeds.vue')['default']
    TableTeachers: typeof import('./src/components/tables/lounge/tableTeachers.vue')['default']
    TableUsers: typeof import('./src/components/tables/general/tableUsers.vue')['default']
  }
}
