/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormAddUser: typeof import('./src/components/formAddUser.vue')['default']
    FormLogin: typeof import('./src/components/formLogin.vue')['default']
    FormUpload: typeof import('./src/components/reports/formUpload.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    NavTest: typeof import('./src/components/navTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    TableAcademic: typeof import('./src/components/tableAcademic.vue')['default']
    TableAssestmentPeriods: typeof import('./src/components/tableAssestmentPeriods.vue')['default']
    TableGroups: typeof import('./src/components/tableGroups.vue')['default']
    TableMembers1: typeof import('./src/components/tableMembers1.vue')['default']
    TableSeedbeds: typeof import('./src/components/tableSeedbeds.vue')['default']
    TableTeachers: typeof import('./src/components/tableTeachers.vue')['default']
    TableUsers: typeof import('./src/components/tableUsers.vue')['default']
    TableUsersProvitional: typeof import('./src/components/tableUsersProvitional.vue')['default']
    TableUsersTest: typeof import('./src/components/tableUsersTest.vue')['default']
  }
}
