/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/academic-programs/': RouteRecordInfo<'/academic-programs/', '/academic-programs', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/reports/': RouteRecordInfo<'/reports/', '/reports', Record<never, never>, Record<never, never>>,
    '/reports/upload': RouteRecordInfo<'/reports/upload', '/reports/upload', Record<never, never>, Record<never, never>>,
    '/research-groups/': RouteRecordInfo<'/research-groups/', '/research-groups', Record<never, never>, Record<never, never>>,
    '/seedbeds/': RouteRecordInfo<'/seedbeds/', '/seedbeds', Record<never, never>, Record<never, never>>,
    '/seedbeds/[id]': RouteRecordInfo<'/seedbeds/[id]', '/seedbeds/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/seedbeds/members1': RouteRecordInfo<'/seedbeds/members1', '/seedbeds/members1', Record<never, never>, Record<never, never>>,
    '/teachers/': RouteRecordInfo<'/teachers/', '/teachers', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/addUser': RouteRecordInfo<'/users/addUser', '/users/addUser', Record<never, never>, Record<never, never>>,
  }
}
