package com.unibegue.magno.model;

public enum LineOfResearch {
    AGRICULTURA_SILVICULTURA_Y_PESCA, ARTE, BIOTECNOLOGIA_AGRICOLA,
    BIOTECNOLOGIA_AMBIENTAL, BIOTECNOLOGIA_EN_SALUD, BIOTECNOLIGIA_INDUSTRIAL,
    CIENCIAS_ANIMALES_Y_LECHERIA, CIENCIAS_BIOLOGICAS, CIENCIAS_DE_LA_EDUCACION,
    CIENCIAS_DE_LA_SALUD, CIENCIAS_DE_LA_TIERRA_Y_MEDIOAMBIENTALES,
    CIENCIAS_FISICAS, CIENCIAS_POLITICAS, CIENCIAS_QUIMICAS, CIENCIAS_VETERINARIAS,
    COMPUTACION_Y_CIENCIAS_DE_LA_INFORMACION, DERECHO, ECONOMIA_Y_NEGOCIOS,
    GEOGRAFIA_SOCIAL_Y_ECONOMIA, HISTORIA_Y_ARQUEOLOGIA, IDIOMAS_Y_LITERATURA,
    INGENIERIA_AMBIENTAL, INGENIERIA_CIVIL, INGENIERIA_DE_LOS_MATERIALES,
    INGENIERIA_MECANICA, INGENIERIA_MEDICA, INGENIERIA_QUIMICA,
    INGENIERIAS_ELECTRICA_ELECTRONICA_E_INFORMATICA, MATEMATICA, MEDICINA_BASICA,
    MEDICINA_CLINICA, NANOTECNOLOGIA, NO_REGISTRA, OTRAS_CIENCIAS_AGRICOLAS,
    OTRAS_CIENCIAS_MEDICAS, OTRAS_CIENCIAS_NATURALES, OTRAS_CIENCIAS_SOCIALES,
    OTRAS_HISTORIAS, OTRAS_HUMANIDADES, OTRAS_INGENIERIAS_Y_TECNOLOGIAS,
    PERIODISMO_Y_COMUNICACIONES, PSICOLOGIA, SOCIOLOGIA
}
