# Application name
spring.application.name=magno-back
server.servlet.context-path=/api

# Port
server.port=8080

# Data jpa
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DB Config
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.url=${JDBC_DATABASE_URL}

# Integra links
integra.base.url=${INTEGRA_BASE_URL}
integra.academic.programs.url=${INTEGRA_ACADEMIC_PROGRAMS_URL}
integra.student.url1=${INTEGRA_STUDENT_URL_1}
integra.student.url2=${INTEGRA_STUDENT_URL_2}
integra.students.all=${INTEGRA_STUDENT_URL_ALL}
integra.all.functionaries.url=${INTEGRA_ALL_FUNCTIONARIES_URL}
integra.all.dependencies.url=${INTEGRA_ALL_DEPENDENCIES_URL}

# Security
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
server.servlet.session.timeout=5m
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

